export enum FLOW_TYPE {
    CREATE_APPOINTMENT = "CREATE_APPOINTMENT",
    EDIT_APPOINTMENT = "EDIT_APPOINTMENT",
    ARRIVE_APPOINTMENT = "ARRIVE_APPOINTMENT",
    CREATE_VISIT = "CREATE_VISIT",
    EDIT_VIST = "EDIT_VIST"
}