export const ERROR_CODE_TIMESLOT_TAKEN = 'E440';
export const ERROR_CODE_APPOINTMENT_NOT_FOUND = 'E142';
export const ERROR_CODE_TIMEOUT = 0;

export enum BLOCKED_ERROR_CODES {
    ERROR_CODE_INVALID_SEARCH_PARAMETER = '8135'
};
